#### The Pandas library is built on NumPy and provides easy-to-use data structures and data analysis tools for the Python programming language.

In [1]:
import pandas as pd

Data Frame is a 2-D data structure with columns capable of holding different data types. 
Creating a Data Frame -

In [2]:
df = pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})
df

   Yes   No
0   50  131
1   21    2

#### Series is a 1-D data structure capable of holding any data type. Creating a series -

In [3]:
pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])

a    3
b   -5
c    7
d    4
dtype: int64

#### Accessing and modifying a dataframe

In [4]:
print('Reading column Yes, row 0 :', df['Yes'][0])
df['Yes'][1] = 25
print('Reading column Yes, row 1 :', df['Yes'][1])

Reading column Yes, row 0 : 50
Reading column Yes, row 1 : 25

#### Reading and writing from a csv

In [5]:
data = pd.read_csv('data/uk-postcode.csv')
df.to_csv('data/myDataFrame.csv')
data

,Postcode,Latitude,Longitude,Easting,Northing,GridRef,Town/Area,Region,Postcodes,Active postcodes,Population,Households
0,AB1,57.1269,-2.136440,391839.0,804005.0,NJ918040,Aberdeen,Aberdeen,2655.0,0.0,NaN,NaN
1,AB2,57.1713,-2.141520,391541.0,808948.0,NJ915089,Aberdeen,Aberdeen,3070.0,0.0,NaN,NaN
2,AB3,57.0876,-2.596240,363963.0,799780.0,NO639997,Aberdeen,Aberdeen,2168.0,0.0,NaN,NaN
3,AB4,57.5343,-2.127130,392487.0,849358.0,NJ924493,"Fraserburgh, Peterhead, Macduff",Aberdeen,2956.0,0.0,NaN,NaN
4,AB5,57.4652,-2.647640,361248.0,841843.0,NJ612418,"Buckie, Huntly, Inverurie",Aberdeen,3002.0,0.0,NaN,NaN
5,AB9,57.1466,-2.114200,393189.0,806196.0,NJ931061,Aberdeen,Aberdeen,1066.0,0.0,NaN,NaN
6,AB10,57.1348,-2.117480,392988.0,804882.0,NJ929048,"Aberdeen city centre, Bridge of Dee, Mannofield",Aberdeen,888.0,675.0,21964.0,11517.0
7,AB11,57.1371,-2.093410,394445.0,805136.0,NJ944051,"Aberdeen city centre, Torry",Aberdeen,889.0,644.0,21237.0,10926.0
8,AB12,57.1033,-2.110340,393414.0,801375.0,NJ934013,"Aberdeen, Altens, Ardoe, Banchory Devenick, Bl...",Aberdeen,991.0,782.0,25414.0,10688.0
9,AB13,57.1127,-2.244690,385279.0,802443.0,NJ852024,Milltimber,Aberdeen,100.0,80.0,2725.0,947.0
10,AB14,57.1033,-2.272510,383590.0,801402.0,NJ835014,"Peterculter, Upper Anguston",Aberdeen,164.0,140.0,4881.0,2162.0
11,AB15,57.1388,-2.165510,390082.0,805334.0,NJ900053,"Aberdeen, Bieldside, Craigiebuckler, Cults, Ha...",Aberdeen,1205.0,1019.0,35543.0,15330.0
12,AB16,57.1596,-2.156540,390630.0,807648.0,NJ906076,"Aberdeen, Mastrick, Northfield, Middlefield, C...",Aberdeen,893.0,776.0,29238.0,12874.0
13,AB21,57.2091,-2.201740,387912.0,813165.0,NJ879131,"Aberdeen, Blackburn, Bucksburn, Dyce, Fintray,...",Aberdeen,879.0,732.0,22181.0,9650.0
14,AB22,57.1864,-2.119130,392898.0,810627.0,NJ928106,"Aberdeen, Bridge of Don, Danestone, Grandholm,...",Aberdeen,361.0,300.0,16311.0,6978.0
15,AB23,57.2088,-2.089710,394680.0,813118.0,NJ946131,"Aberdeen, Balmedie, Belhelvie, Bridge of Don, ...",Aberdeen,399.0,311.0,11143.0,4517.0
16,AB24,57.1634,-2.108280,393550.0,808065.0,NJ935080,"Aberdeen, Old Aberdeen, Woodside, Tillydrone, ...",Aberdeen,968.0,808.0,36343.0,16935.0
17,AB25,57.1534,-2.114220,393189.0,806953.0,NJ931069,"Aberdeen city centre, Kittybrewster, Foresterh...",Aberdeen,610.0,476.0,18407.0,9634.0
18,AB30,56.8460,-2.477260,370986.0,772829.0,NO709728,Laurencekirk,Aberdeenshire,349.0,308.0,7229.0,2935.0
19,AB31,57.0672,-2.505520,369444.0,797465.0,NO694974,Banchory,Aberdeenshire,1033.0,629.0,15319.0,6096.0
20,AB32,57.1546,-2.315040,381040.0,807124.0,NJ810071,Westhill,Aberdeenshire,422.0,365.0,12902.0,5011.0
21,AB33,57.2259,-2.737340,355578.0,815258.0,NJ555152,Alford,Aberdeenshire,305.0,268.0,5273.0,2180.0
22,AB34,57.0929,-2.811410,350930.0,800504.0,NJ509005,Aboyne,Aberdeenshire,292.0,266.0,5387.0,2309.0
23,AB35,57.0389,-3.144620,330638.0,794783.0,NO306947,Ballater,Aberdeenshire,201.0,166.0,2624.0,1217.0
24,AB36,57.1962,-3.072080,335315.0,812221.0,NJ353122,Strathdon,Aberdeenshire,55.0,47.0,515.0,242.0
25,AB37,57.3318,-3.352720,318658.0,827616.0,NJ186276,Ballindalloch,Moray,94.0,86.0,1534.0,678.0
26,AB38,57.4855,-3.227400,326511.0,844582.0,NJ265445,Aberlour,Moray,182.0,162.0,4660.0,2009.0
27,AB39,56.9777,-2.217230,386894.0,787409.0,NO868874,"Stonehaven, Newtonhill",Aberdeenshire,579.0,516.0,17645.0,7238.0
28,AB41,57.3725,-2.117950,393005.0,831344.0,NJ930313,Ellon,Aberdeenshire,1147.0,788.0,20837.0,8517.0
29,AB42,57.5016,-1.888290,406794.0,845715.0,NK067457,"Hatton, St. Fergus",Aberdeenshire,2373.0,1215.0,33730.0,14367.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3077,YO12,54.2744,-0.422116,502845.0,487676.0,TA028876,Seamer,North Yorkshire,1091.0,866.0,40749.0,17709.0
3078,YO13,54.2875,-0.493908,498139.0,489031.0,SE981890,Scarborough,North Yorkshire,437.0,384.0,9923.0,4431.0
3079,YO14,54.1998,-0.298415,511099.0,479564.0,TA110795,Filey,North Yorkshire,497.0,388.0,11294.0,5394.0
3080,YO15,54.0916,-0.182294,518983.0,467715.0,TA189677,"Bridlington, Bempton, Buckton, Carnaby, Flambo...",East Riding of Yorkshire,679.0,483.0,14085.0,6466.0
3081,YO16,54.0961,-0.199037,517875.0,468188.0,TA178681,"Bridlington, Bempton, Bessingby, Boynton, Buck...",East Riding of Yorkshire,1121.0,655.0,25109.0,11534.0
3082,YO17,54.1396,-0.771188,480376.0,472226.0,SE803722,Norton,North Yorkshire,1235.0,786.0,21248.0,9171.0
3083,YO18,54.2563,-0.767644,480382.0,485215.0,SE803852,Thornton-le-Dale,North Yorkshire,516.0,418.0,10870.0,4917.0
3084,YO19,53.9114,-1.026150,464069.0,446578.0,SE640465,"Dunnington, Escrick, Wheldrake, Murton, Riccal...",York,544.0,460.0,12740.0,5051.0
3085,YO21,54.4779,-0.702582,484166.0,509946.0,NZ841099,"Whitby, Westerdale",North Yorkshire,758.0,648.0,14415.0,6543.0
3086,YO22,54.4525,-0.621883,489450.0,507219.0,NZ894072,Robin Hood's Bay,North Yorkshire,463.0,411.0,8538.0,3790.0
3087,YO23,53.9276,-1.119850,457892.0,448300.0,SE578482,"South Bank, Bishopthorpe, Copmanthorpe, Rufforth",York,675.0,561.0,19389.0,8539.0
3088,YO24,53.9473,-1.114270,458231.0,450496.0,SE582504,"Acomb, Dringhouses, Woodthorpe",York,821.0,687.0,29671.0,13170.0
3089,YO25,54.0146,-0.419138,503685.0,458777.0,TA036587,Driffield,East Riding of Yorkshire,2122.0,1257.0,33428.0,14505.0
3090,YO26,53.9737,-1.164670,454889.0,453393.0,SE548533,"Acomb, Leeman Road Area, Upper Poppleton, Neth...",York,1133.0,849.0,30456.0,12680.0
3091,YO30,53.9840,-1.110990,458395.0,454582.0,SE583545,"Bootham, Clifton, Skelton, Linton-on-Ouse",York,854.0,677.0,26723.0,11233.0
3092,YO31,53.9701,-1.066060,461362.0,453073.0,SE613530,"Heworth, Huntington (South), The Groves, Layer...",York,973.0,783.0,29605.0,12683.0
3093,YO32,54.0090,-1.060380,461677.0,457406.0,SE616574,"Haxby, Huntington (North), Wigginton, New Ears...",York,901.0,789.0,28568.0,12247.0
3094,YO41,53.9687,-0.910593,471562.0,453063.0,SE715530,"Elvington, Full Sutton, Stamford Bridge, Sutto...",York,481.0,409.0,10963.0,4241.0
3095,YO42,53.9246,-0.788898,479629.0,448286.0,SE796482,"Pocklington, Barmby Moor, Melbourne, Seaton Ross",East Riding of Yorkshire,723.0,600.0,14451.0,6116.0
3096,YO43,53.8504,-0.684112,486663.0,440154.0,SE866401,"Market Weighton, Holme-on-Spalding-Moor",East Riding of Yorkshire,500.0,439.0,12311.0,5232.0
3097,YO51,54.0871,-1.387740,440148.0,465861.0,SE401658,Boroughbridge,North Yorkshire,284.0,217.0,5543.0,2367.0
3098,YO60,54.0846,-0.946931,468987.0,465922.0,SE689659,Skewsby,York,304.0,257.0,4583.0,2042.0
3099,YO61,54.1196,-1.199300,452434.0,469600.0,SE524695,Easingwold,North Yorkshire,713.0,636.0,13914.0,5939.0
3100,YO62,54.2446,-0.995248,465573.0,483677.0,SE655836,"Thorpe Hall, Helmsley. Kirkbymoorside",North Yorkshire,670.0,600.0,11979.0,5116.0
3101,YO90,53.9599,-1.090960,459743.0,451917.0,SE597519,"Rougier St, Wellington Row",York,18.0,11.0,NaN,NaN
3102,YO91,53.9779,-1.066370,461330.0,453941.0,SE613539,"Lawrence Court, PO Boxes",York,10.0,1.0,NaN,NaN
3103,YO95,53.9267,-0.815105,477904.0,448491.0,SE779484,Pocklington,York,1.0,0.0,NaN,NaN
3104,ZE1,60.1530,-1.167710,446309.0,1141237.0,HU463412,"Lerwick, Scalloway",Shetland,392.0,330.0,8445.0,3862.0
3105,ZE2,60.3156,-1.228710,442711.0,1159304.0,HU427593,Shetland,Shetland,335.0,305.0,14209.0,5845.0
3106,ZE3,59.8833,-1.304610,439025.0,1111113.0,HU390111,Bush,Shetland,13.0,12.0,432.0,208.0

In [6]:
data[3100:] # accessing data after row number 3100

,Postcode,Latitude,Longitude,Easting,Northing,GridRef,Town/Area,Region,Postcodes,Active postcodes,Population,Households
3100,YO62,54.2446,-0.995248,465573.0,483677.0,SE655836,"Thorpe Hall, Helmsley. Kirkbymoorside",North Yorkshire,670.0,600.0,11979.0,5116.0
3101,YO90,53.9599,-1.090960,459743.0,451917.0,SE597519,"Rougier St, Wellington Row",York,18.0,11.0,NaN,NaN
3102,YO91,53.9779,-1.066370,461330.0,453941.0,SE613539,"Lawrence Court, PO Boxes",York,10.0,1.0,NaN,NaN
3103,YO95,53.9267,-0.815105,477904.0,448491.0,SE779484,Pocklington,York,1.0,0.0,NaN,NaN
3104,ZE1,60.1530,-1.167710,446309.0,1141237.0,HU463412,"Lerwick, Scalloway",Shetland,392.0,330.0,8445.0,3862.0
3105,ZE2,60.3156,-1.228710,442711.0,1159304.0,HU427593,Shetland,Shetland,335.0,305.0,14209.0,5845.0
3106,ZE3,59.8833,-1.304610,439025.0,1111113.0,HU390111,Bush,Shetland,13.0,12.0,432.0,208.0

In [7]:
data[:-5] # ignoring the last 5 rows

,Postcode,Latitude,Longitude,Easting,Northing,GridRef,Town/Area,Region,Postcodes,Active postcodes,Population,Households
0,AB1,57.1269,-2.136440,391839.0,804005.0,NJ918040,Aberdeen,Aberdeen,2655.0,0.0,NaN,NaN
1,AB2,57.1713,-2.141520,391541.0,808948.0,NJ915089,Aberdeen,Aberdeen,3070.0,0.0,NaN,NaN
2,AB3,57.0876,-2.596240,363963.0,799780.0,NO639997,Aberdeen,Aberdeen,2168.0,0.0,NaN,NaN
3,AB4,57.5343,-2.127130,392487.0,849358.0,NJ924493,"Fraserburgh, Peterhead, Macduff",Aberdeen,2956.0,0.0,NaN,NaN
4,AB5,57.4652,-2.647640,361248.0,841843.0,NJ612418,"Buckie, Huntly, Inverurie",Aberdeen,3002.0,0.0,NaN,NaN
5,AB9,57.1466,-2.114200,393189.0,806196.0,NJ931061,Aberdeen,Aberdeen,1066.0,0.0,NaN,NaN
6,AB10,57.1348,-2.117480,392988.0,804882.0,NJ929048,"Aberdeen city centre, Bridge of Dee, Mannofield",Aberdeen,888.0,675.0,21964.0,11517.0
7,AB11,57.1371,-2.093410,394445.0,805136.0,NJ944051,"Aberdeen city centre, Torry",Aberdeen,889.0,644.0,21237.0,10926.0
8,AB12,57.1033,-2.110340,393414.0,801375.0,NJ934013,"Aberdeen, Altens, Ardoe, Banchory Devenick, Bl...",Aberdeen,991.0,782.0,25414.0,10688.0
9,AB13,57.1127,-2.244690,385279.0,802443.0,NJ852024,Milltimber,Aberdeen,100.0,80.0,2725.0,947.0
10,AB14,57.1033,-2.272510,383590.0,801402.0,NJ835014,"Peterculter, Upper Anguston",Aberdeen,164.0,140.0,4881.0,2162.0
11,AB15,57.1388,-2.165510,390082.0,805334.0,NJ900053,"Aberdeen, Bieldside, Craigiebuckler, Cults, Ha...",Aberdeen,1205.0,1019.0,35543.0,15330.0
12,AB16,57.1596,-2.156540,390630.0,807648.0,NJ906076,"Aberdeen, Mastrick, Northfield, Middlefield, C...",Aberdeen,893.0,776.0,29238.0,12874.0
13,AB21,57.2091,-2.201740,387912.0,813165.0,NJ879131,"Aberdeen, Blackburn, Bucksburn, Dyce, Fintray,...",Aberdeen,879.0,732.0,22181.0,9650.0
14,AB22,57.1864,-2.119130,392898.0,810627.0,NJ928106,"Aberdeen, Bridge of Don, Danestone, Grandholm,...",Aberdeen,361.0,300.0,16311.0,6978.0
15,AB23,57.2088,-2.089710,394680.0,813118.0,NJ946131,"Aberdeen, Balmedie, Belhelvie, Bridge of Don, ...",Aberdeen,399.0,311.0,11143.0,4517.0
16,AB24,57.1634,-2.108280,393550.0,808065.0,NJ935080,"Aberdeen, Old Aberdeen, Woodside, Tillydrone, ...",Aberdeen,968.0,808.0,36343.0,16935.0
17,AB25,57.1534,-2.114220,393189.0,806953.0,NJ931069,"Aberdeen city centre, Kittybrewster, Foresterh...",Aberdeen,610.0,476.0,18407.0,9634.0
18,AB30,56.8460,-2.477260,370986.0,772829.0,NO709728,Laurencekirk,Aberdeenshire,349.0,308.0,7229.0,2935.0
19,AB31,57.0672,-2.505520,369444.0,797465.0,NO694974,Banchory,Aberdeenshire,1033.0,629.0,15319.0,6096.0
20,AB32,57.1546,-2.315040,381040.0,807124.0,NJ810071,Westhill,Aberdeenshire,422.0,365.0,12902.0,5011.0
21,AB33,57.2259,-2.737340,355578.0,815258.0,NJ555152,Alford,Aberdeenshire,305.0,268.0,5273.0,2180.0
22,AB34,57.0929,-2.811410,350930.0,800504.0,NJ509005,Aboyne,Aberdeenshire,292.0,266.0,5387.0,2309.0
23,AB35,57.0389,-3.144620,330638.0,794783.0,NO306947,Ballater,Aberdeenshire,201.0,166.0,2624.0,1217.0
24,AB36,57.1962,-3.072080,335315.0,812221.0,NJ353122,Strathdon,Aberdeenshire,55.0,47.0,515.0,242.0
25,AB37,57.3318,-3.352720,318658.0,827616.0,NJ186276,Ballindalloch,Moray,94.0,86.0,1534.0,678.0
26,AB38,57.4855,-3.227400,326511.0,844582.0,NJ265445,Aberlour,Moray,182.0,162.0,4660.0,2009.0
27,AB39,56.9777,-2.217230,386894.0,787409.0,NO868874,"Stonehaven, Newtonhill",Aberdeenshire,579.0,516.0,17645.0,7238.0
28,AB41,57.3725,-2.117950,393005.0,831344.0,NJ930313,Ellon,Aberdeenshire,1147.0,788.0,20837.0,8517.0
29,AB42,57.5016,-1.888290,406794.0,845715.0,NK067457,"Hatton, St. Fergus",Aberdeenshire,2373.0,1215.0,33730.0,14367.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3072,YO6,54.1544,-1.080350,460158.0,473566.0,SE601735,"Helmsley, Easingwold",York,1580.0,0.0,NaN,NaN
3073,YO7,54.2246,-1.350100,442470.0,481182.0,SE424811,Thirsk,North Yorkshire,1077.0,896.0,20048.0,8347.0
3074,YO8,53.7855,-1.056520,462261.0,432543.0,SE622325,"Barlby, Brayton, Bubwith, Cawood, Camblesforth...",York,2128.0,1245.0,43547.0,18145.0
3075,YO10,53.9514,-1.060770,461736.0,450997.0,SE617509,"Fishergate, Fulford, Heslington, Osbaldwick, T...",York,767.0,637.0,30543.0,10702.0
3076,YO11,54.2691,-0.398449,504399.0,487121.0,TA043871,Cayton,North Yorkshire,1106.0,734.0,23199.0,11192.0
3077,YO12,54.2744,-0.422116,502845.0,487676.0,TA028876,Seamer,North Yorkshire,1091.0,866.0,40749.0,17709.0
3078,YO13,54.2875,-0.493908,498139.0,489031.0,SE981890,Scarborough,North Yorkshire,437.0,384.0,9923.0,4431.0
3079,YO14,54.1998,-0.298415,511099.0,479564.0,TA110795,Filey,North Yorkshire,497.0,388.0,11294.0,5394.0
3080,YO15,54.0916,-0.182294,518983.0,467715.0,TA189677,"Bridlington, Bempton, Buckton, Carnaby, Flambo...",East Riding of Yorkshire,679.0,483.0,14085.0,6466.0
3081,YO16,54.0961,-0.199037,517875.0,468188.0,TA178681,"Bridlington, Bempton, Bessingby, Boynton, Buck...",East Riding of Yorkshire,1121.0,655.0,25109.0,11534.0
3082,YO17,54.1396,-0.771188,480376.0,472226.0,SE803722,Norton,North Yorkshire,1235.0,786.0,21248.0,9171.0
3083,YO18,54.2563,-0.767644,480382.0,485215.0,SE803852,Thornton-le-Dale,North Yorkshire,516.0,418.0,10870.0,4917.0
3084,YO19,53.9114,-1.026150,464069.0,446578.0,SE640465,"Dunnington, Escrick, Wheldrake, Murton, Riccal...",York,544.0,460.0,12740.0,5051.0
3085,YO21,54.4779,-0.702582,484166.0,509946.0,NZ841099,"Whitby, Westerdale",North Yorkshire,758.0,648.0,14415.0,6543.0
3086,YO22,54.4525,-0.621883,489450.0,507219.0,NZ894072,Robin Hood's Bay,North Yorkshire,463.0,411.0,8538.0,3790.0
3087,YO23,53.9276,-1.119850,457892.0,448300.0,SE578482,"South Bank, Bishopthorpe, Copmanthorpe, Rufforth",York,675.0,561.0,19389.0,8539.0
3088,YO24,53.9473,-1.114270,458231.0,450496.0,SE582504,"Acomb, Dringhouses, Woodthorpe",York,821.0,687.0,29671.0,13170.0
3089,YO25,54.0146,-0.419138,503685.0,458777.0,TA036587,Driffield,East Riding of Yorkshire,2122.0,1257.0,33428.0,14505.0
3090,YO26,53.9737,-1.164670,454889.0,453393.0,SE548533,"Acomb, Leeman Road Area, Upper Poppleton, Neth...",York,1133.0,849.0,30456.0,12680.0
3091,YO30,53.9840,-1.110990,458395.0,454582.0,SE583545,"Bootham, Clifton, Skelton, Linton-on-Ouse",York,854.0,677.0,26723.0,11233.0
3092,YO31,53.9701,-1.066060,461362.0,453073.0,SE613530,"Heworth, Huntington (South), The Groves, Layer...",York,973.0,783.0,29605.0,12683.0
3093,YO32,54.0090,-1.060380,461677.0,457406.0,SE616574,"Haxby, Huntington (North), Wigginton, New Ears...",York,901.0,789.0,28568.0,12247.0
3094,YO41,53.9687,-0.910593,471562.0,453063.0,SE715530,"Elvington, Full Sutton, Stamford Bridge, Sutto...",York,481.0,409.0,10963.0,4241.0
3095,YO42,53.9246,-0.788898,479629.0,448286.0,SE796482,"Pocklington, Barmby Moor, Melbourne, Seaton Ross",East Riding of Yorkshire,723.0,600.0,14451.0,6116.0
3096,YO43,53.8504,-0.684112,486663.0,440154.0,SE866401,"Market Weighton, Holme-on-Spalding-Moor",East Riding of Yorkshire,500.0,439.0,12311.0,5232.0
3097,YO51,54.0871,-1.387740,440148.0,465861.0,SE401658,Boroughbridge,North Yorkshire,284.0,217.0,5543.0,2367.0
3098,YO60,54.0846,-0.946931,468987.0,465922.0,SE689659,Skewsby,York,304.0,257.0,4583.0,2042.0
3099,YO61,54.1196,-1.199300,452434.0,469600.0,SE524695,Easingwold,North Yorkshire,713.0,636.0,13914.0,5939.0
3100,YO62,54.2446,-0.995248,465573.0,483677.0,SE655836,"Thorpe Hall, Helmsley. Kirkbymoorside",North Yorkshire,670.0,600.0,11979.0,5116.0
3101,YO90,53.9599,-1.090960,459743.0,451917.0,SE597519,"Rougier St, Wellington Row",York,18.0,11.0,NaN,NaN

#### The list of row labels used in a DataFrame is known as an Index. We can assign values to it by using an index parameter in our constructor:

In [8]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']}, index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [9]:
series = pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')
series['2015 Sales']

30

In [10]:
print('shape attribute can be used for describing how large the resulting dataframe is')
data.shape

shape attribute can be used for describing how large the resulting dataframe is

(3107, 12)

In [11]:
print('index attribute can be used for describing the index of dataframe')
print(series.index)

index attribute can be used for describing the index of dataframe
Index(['2015 Sales', '2016 Sales', '2017 Sales'], dtype='object')

In [12]:
print('columns attribute can be used for describing the columns of dataframe')
print(data.columns)

columns attribute can be used for describing the columns of dataframe
Index(['Postcode', 'Latitude', 'Longitude', 'Easting', 'Northing', 'GridRef',
       'Town/Area', 'Region', 'Postcodes', 'Active postcodes', 'Population',
       'Households'],
      dtype='object')

In [13]:
print('info method gives us the meta data of dataframe')
print(data.info())

info method gives us the meta data of dataframe
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3107 entries, 0 to 3106
Data columns (total 12 columns):
Postcode            3107 non-null object
Latitude            3094 non-null float64
Longitude           3094 non-null float64
Easting             3082 non-null float64
Northing            3082 non-null float64
GridRef             3082 non-null object
Town/Area           3107 non-null object
Region              3106 non-null object
Postcodes           3086 non-null float64
Active postcodes    3086 non-null float64
Population          2814 non-null float64
Households          2814 non-null float64
dtypes: float64(8), object(4)
memory usage: 291.4+ KB
None

In [14]:
print('count gives us the number of non- N/A values')
data.count()

count gives us the number of non- N/A values

Postcode            3107
Latitude            3094
Longitude           3094
Easting             3082
Northing            3082
GridRef             3082
Town/Area           3107
Region              3106
Postcodes           3086
Active postcodes    3086
Population          2814
Households          2814
dtype: int64

In [15]:
print('head grabs the first five rows of the dataframe')
data.head()

head grabs the first five rows of the dataframe

,Postcode,Latitude,Longitude,Easting,Northing,GridRef,Town/Area,Region,Postcodes,Active postcodes,Population,Households
0,AB1,57.1269,-2.13644,391839.0,804005.0,NJ918040,Aberdeen,Aberdeen,2655.0,0.0,NaN,NaN
1,AB2,57.1713,-2.14152,391541.0,808948.0,NJ915089,Aberdeen,Aberdeen,3070.0,0.0,NaN,NaN
2,AB3,57.0876,-2.59624,363963.0,799780.0,NO639997,Aberdeen,Aberdeen,2168.0,0.0,NaN,NaN
3,AB4,57.5343,-2.12713,392487.0,849358.0,NJ924493,"Fraserburgh, Peterhead, Macduff",Aberdeen,2956.0,0.0,NaN,NaN
4,AB5,57.4652,-2.64764,361248.0,841843.0,NJ612418,"Buckie, Huntly, Inverurie",Aberdeen,3002.0,0.0,NaN,NaN

In [17]:
cols = ['Postcode', 'Town/Area', 'Region']
indices = [0, 1, 10, 100]
data.loc[indices, cols]

    Postcode                    Town/Area    Region
0        AB1                     Aberdeen  Aberdeen
1        AB2                     Aberdeen  Aberdeen
10      AB14  Peterculter, Upper Anguston  Aberdeen
100      B62                    Halesowen    Dudley